#if 0
#elif defined(__arm64__) && __arm64__
// Generated by Apple Swift version 5.2.4 effective-4.1.50 (swiftlang-1103.0.32.9 clang-1103.0.32.53)
#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wgcc-compat"

#if !defined(__has_include)
# define __has_include(x) 0
#endif
#if !defined(__has_attribute)
# define __has_attribute(x) 0
#endif
#if !defined(__has_feature)
# define __has_feature(x) 0
#endif
#if !defined(__has_warning)
# define __has_warning(x) 0
#endif

#if __has_include(<swift/objc-prologue.h>)
# include <swift/objc-prologue.h>
#endif

#pragma clang diagnostic ignored "-Wauto-import"
#include <Foundation/Foundation.h>
#include <stdint.h>
#include <stddef.h>
#include <stdbool.h>

#if !defined(SWIFT_TYPEDEFS)
# define SWIFT_TYPEDEFS 1
# if __has_include(<uchar.h>)
#  include <uchar.h>
# elif !defined(__cplusplus)
typedef uint_least16_t char16_t;
typedef uint_least32_t char32_t;
# endif
typedef float swift_float2  __attribute__((__ext_vector_type__(2)));
typedef float swift_float3  __attribute__((__ext_vector_type__(3)));
typedef float swift_float4  __attribute__((__ext_vector_type__(4)));
typedef double swift_double2  __attribute__((__ext_vector_type__(2)));
typedef double swift_double3  __attribute__((__ext_vector_type__(3)));
typedef double swift_double4  __attribute__((__ext_vector_type__(4)));
typedef int swift_int2  __attribute__((__ext_vector_type__(2)));
typedef int swift_int3  __attribute__((__ext_vector_type__(3)));
typedef int swift_int4  __attribute__((__ext_vector_type__(4)));
typedef unsigned int swift_uint2  __attribute__((__ext_vector_type__(2)));
typedef unsigned int swift_uint3  __attribute__((__ext_vector_type__(3)));
typedef unsigned int swift_uint4  __attribute__((__ext_vector_type__(4)));
#endif

#if !defined(SWIFT_PASTE)
# define SWIFT_PASTE_HELPER(x, y) x##y
# define SWIFT_PASTE(x, y) SWIFT_PASTE_HELPER(x, y)
#endif
#if !defined(SWIFT_METATYPE)
# define SWIFT_METATYPE(X) Class
#endif
#if !defined(SWIFT_CLASS_PROPERTY)
# if __has_feature(objc_class_property)
#  define SWIFT_CLASS_PROPERTY(...) __VA_ARGS__
# else
#  define SWIFT_CLASS_PROPERTY(...)
# endif
#endif

#if __has_attribute(objc_runtime_name)
# define SWIFT_RUNTIME_NAME(X) __attribute__((objc_runtime_name(X)))
#else
# define SWIFT_RUNTIME_NAME(X)
#endif
#if __has_attribute(swift_name)
# define SWIFT_COMPILE_NAME(X) __attribute__((swift_name(X)))
#else
# define SWIFT_COMPILE_NAME(X)
#endif
#if __has_attribute(objc_method_family)
# define SWIFT_METHOD_FAMILY(X) __attribute__((objc_method_family(X)))
#else
# define SWIFT_METHOD_FAMILY(X)
#endif
#if __has_attribute(noescape)
# define SWIFT_NOESCAPE __attribute__((noescape))
#else
# define SWIFT_NOESCAPE
#endif
#if __has_attribute(ns_consumed)
# define SWIFT_RELEASES_ARGUMENT __attribute__((ns_consumed))
#else
# define SWIFT_RELEASES_ARGUMENT
#endif
#if __has_attribute(warn_unused_result)
# define SWIFT_WARN_UNUSED_RESULT __attribute__((warn_unused_result))
#else
# define SWIFT_WARN_UNUSED_RESULT
#endif
#if __has_attribute(noreturn)
# define SWIFT_NORETURN __attribute__((noreturn))
#else
# define SWIFT_NORETURN
#endif
#if !defined(SWIFT_CLASS_EXTRA)
# define SWIFT_CLASS_EXTRA
#endif
#if !defined(SWIFT_PROTOCOL_EXTRA)
# define SWIFT_PROTOCOL_EXTRA
#endif
#if !defined(SWIFT_ENUM_EXTRA)
# define SWIFT_ENUM_EXTRA
#endif
#if !defined(SWIFT_CLASS)
# if __has_attribute(objc_subclassing_restricted)
#  define SWIFT_CLASS(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) __attribute__((objc_subclassing_restricted)) SWIFT_CLASS_EXTRA
#  define SWIFT_CLASS_NAMED(SWIFT_NAME) __attribute__((objc_subclassing_restricted)) SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_CLASS_EXTRA
# else
#  define SWIFT_CLASS(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) SWIFT_CLASS_EXTRA
#  define SWIFT_CLASS_NAMED(SWIFT_NAME) SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_CLASS_EXTRA
# endif
#endif
#if !defined(SWIFT_RESILIENT_CLASS)
# if __has_attribute(objc_class_stub)
#  define SWIFT_RESILIENT_CLASS(SWIFT_NAME) SWIFT_CLASS(SWIFT_NAME) __attribute__((objc_class_stub))
#  define SWIFT_RESILIENT_CLASS_NAMED(SWIFT_NAME) __attribute__((objc_class_stub)) SWIFT_CLASS_NAMED(SWIFT_NAME)
# else
#  define SWIFT_RESILIENT_CLASS(SWIFT_NAME) SWIFT_CLASS(SWIFT_NAME)
#  define SWIFT_RESILIENT_CLASS_NAMED(SWIFT_NAME) SWIFT_CLASS_NAMED(SWIFT_NAME)
# endif
#endif

#if !defined(SWIFT_PROTOCOL)
# define SWIFT_PROTOCOL(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) SWIFT_PROTOCOL_EXTRA
# define SWIFT_PROTOCOL_NAMED(SWIFT_NAME) SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_PROTOCOL_EXTRA
#endif

#if !defined(SWIFT_EXTENSION)
# define SWIFT_EXTENSION(M) SWIFT_PASTE(M##_Swift_, __LINE__)
#endif

#if !defined(OBJC_DESIGNATED_INITIALIZER)
# if __has_attribute(objc_designated_initializer)
#  define OBJC_DESIGNATED_INITIALIZER __attribute__((objc_designated_initializer))
# else
#  define OBJC_DESIGNATED_INITIALIZER
# endif
#endif
#if !defined(SWIFT_ENUM_ATTR)
# if defined(__has_attribute) && __has_attribute(enum_extensibility)
#  define SWIFT_ENUM_ATTR(_extensibility) __attribute__((enum_extensibility(_extensibility)))
# else
#  define SWIFT_ENUM_ATTR(_extensibility)
# endif
#endif
#if !defined(SWIFT_ENUM)
# define SWIFT_ENUM(_type, _name, _extensibility) enum _name : _type _name; enum SWIFT_ENUM_ATTR(_extensibility) SWIFT_ENUM_EXTRA _name : _type
# if __has_feature(generalized_swift_name)
#  define SWIFT_ENUM_NAMED(_type, _name, SWIFT_NAME, _extensibility) enum _name : _type _name SWIFT_COMPILE_NAME(SWIFT_NAME); enum SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_ENUM_ATTR(_extensibility) SWIFT_ENUM_EXTRA _name : _type
# else
#  define SWIFT_ENUM_NAMED(_type, _name, SWIFT_NAME, _extensibility) SWIFT_ENUM(_type, _name, _extensibility)
# endif
#endif
#if !defined(SWIFT_UNAVAILABLE)
# define SWIFT_UNAVAILABLE __attribute__((unavailable))
#endif
#if !defined(SWIFT_UNAVAILABLE_MSG)
# define SWIFT_UNAVAILABLE_MSG(msg) __attribute__((unavailable(msg)))
#endif
#if !defined(SWIFT_AVAILABILITY)
# define SWIFT_AVAILABILITY(plat, ...) __attribute__((availability(plat, __VA_ARGS__)))
#endif
#if !defined(SWIFT_WEAK_IMPORT)
# define SWIFT_WEAK_IMPORT __attribute__((weak_import))
#endif
#if !defined(SWIFT_DEPRECATED)
# define SWIFT_DEPRECATED __attribute__((deprecated))
#endif
#if !defined(SWIFT_DEPRECATED_MSG)
# define SWIFT_DEPRECATED_MSG(...) __attribute__((deprecated(__VA_ARGS__)))
#endif
#if __has_feature(attribute_diagnose_if_objc)
# define SWIFT_DEPRECATED_OBJC(Msg) __attribute__((diagnose_if(1, Msg, "warning")))
#else
# define SWIFT_DEPRECATED_OBJC(Msg) SWIFT_DEPRECATED_MSG(Msg)
#endif
#if !defined(IBSegueAction)
# define IBSegueAction
#endif
#if __has_feature(modules)
#if __has_warning("-Watimport-in-framework-header")
#pragma clang diagnostic ignored "-Watimport-in-framework-header"
#endif
@import CoreGraphics;
@import Foundation;
@import ObjectiveC;
@import UIKit;
#endif

#import <YaokanUISDK/YaokanUISDK.h>

#pragma clang diagnostic ignored "-Wproperty-attribute-mismatch"
#pragma clang diagnostic ignored "-Wduplicate-method-arg"
#if __has_warning("-Wpragma-clang-attribute")
# pragma clang diagnostic ignored "-Wpragma-clang-attribute"
#endif
#pragma clang diagnostic ignored "-Wunknown-pragmas"
#pragma clang diagnostic ignored "-Wnullability"

#if __has_attribute(external_source_symbol)
# pragma push_macro("any")
# undef any
# pragma clang attribute push(__attribute__((external_source_symbol(language="Swift", defined_in="YaokanUISDK",generated_declaration))), apply_to=any(function,enum,objc_interface,objc_category,objc_protocol))
# pragma pop_macro("any")
#endif

@class UILabel;
@class UIButton;
@class UIImageView;
@class NSLayoutConstraint;
@class NSCoder;

SWIFT_CLASS("_TtC11YaokanUISDK19LearnTipsBottomView")
@interface LearnTipsBottomView : UIView
@property (nonatomic, weak) IBOutlet UILabel * _Null_unspecified contentLabel;
@property (nonatomic, weak) IBOutlet UIButton * _Null_unspecified doneButton;
@property (nonatomic, weak) IBOutlet UIImageView * _Null_unspecified learnGuideView;
@property (nonatomic, weak) IBOutlet UIImageView * _Null_unspecified tapView;
@property (nonatomic, strong) IBOutlet NSLayoutConstraint * _Null_unspecified leadingCons;
- (void)hideDoneButtonWithHide:(BOOL)hide;
- (void)step1;
- (void)step2;
- (void)step3;
- (void)step4;
- (nonnull instancetype)initWithFrame:(CGRect)frame OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)coder OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC11YaokanUISDK13OSMBottomView")
@interface OSMBottomView : UIView
@property (nonatomic, weak) IBOutlet UIButton * _Null_unspecified falseButton;
@property (nonatomic, weak) IBOutlet UIButton * _Null_unspecified trueButton;
@property (nonatomic, weak) IBOutlet UILabel * _Null_unspecified progressLabel;
@property (nonatomic, weak) IBOutlet UILabel * _Null_unspecified contentLabel;
@property (nonatomic, weak) IBOutlet UIButton * _Null_unspecified doneBtn;
- (nonnull instancetype)initWithFrame:(CGRect)frame OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)coder OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC11YaokanUISDK22RCRoomInfoReusableView")
@interface RCRoomInfoReusableView : UICollectionReusableView
- (void)awakeFromNib;
- (nonnull instancetype)initWithFrame:(CGRect)frame OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)coder OBJC_DESIGNATED_INITIALIZER;
@end

@class UITableView;
@class UITableViewCell;
@class NSBundle;

SWIFT_CLASS("_TtC11YaokanUISDK26RCRoomNamePickerController")
@interface RCRoomNamePickerController : UITableViewController
- (void)viewDidLoad;
- (NSInteger)tableView:(UITableView * _Nonnull)tableView numberOfRowsInSection:(NSInteger)section SWIFT_WARN_UNUSED_RESULT;
- (UITableViewCell * _Nonnull)tableView:(UITableView * _Nonnull)tableView cellForRowAtIndexPath:(NSIndexPath * _Nonnull)indexPath SWIFT_WARN_UNUSED_RESULT;
- (void)tableView:(UITableView * _Nonnull)tableView didSelectRowAtIndexPath:(NSIndexPath * _Nonnull)indexPath;
- (nonnull instancetype)initWithStyle:(UITableViewStyle)style OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)initWithNibName:(NSString * _Nullable)nibNameOrNil bundle:(NSBundle * _Nullable)nibBundleOrNil OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)coder OBJC_DESIGNATED_INITIALIZER;
@end

@protocol RCRoomSelectViewControllerDelegate;
@class YKRemoteDevice;
@class NSNumber;
@class UIStoryboardSegue;
@class UICollectionView;
@class UICollectionViewCell;
@class UICollectionViewLayout;

SWIFT_CLASS("_TtC11YaokanUISDK26RCRoomSelectViewController")
@interface RCRoomSelectViewController : UICollectionViewController
@property (nonatomic, weak) id <RCRoomSelectViewControllerDelegate> _Nullable delegate;
@property (nonatomic, strong) YKRemoteDevice * _Nullable remoteDevice;
@property (nonatomic, strong) NSNumber * _Nullable isCreate;
- (void)viewDidLoad;
- (void)viewDidAppear:(BOOL)animated;
- (void)viewDidDisappear:(BOOL)animated;
@property (nonatomic, readonly) UIStatusBarStyle preferredStatusBarStyle;
@property (nonatomic, readonly) BOOL shouldAutorotate;
@property (nonatomic, readonly) UIInterfaceOrientationMask supportedInterfaceOrientations;
- (void)prepareForSegue:(UIStoryboardSegue * _Nonnull)segue sender:(id _Nullable)sender;
- (NSInteger)collectionView:(UICollectionView * _Nonnull)collectionView numberOfItemsInSection:(NSInteger)section SWIFT_WARN_UNUSED_RESULT;
- (UICollectionViewCell * _Nonnull)collectionView:(UICollectionView * _Nonnull)collectionView cellForItemAtIndexPath:(NSIndexPath * _Nonnull)indexPath SWIFT_WARN_UNUSED_RESULT;
- (UICollectionReusableView * _Nonnull)collectionView:(UICollectionView * _Nonnull)collectionView viewForSupplementaryElementOfKind:(NSString * _Nonnull)kind atIndexPath:(NSIndexPath * _Nonnull)indexPath SWIFT_WARN_UNUSED_RESULT;
- (void)collectionView:(UICollectionView * _Nonnull)collectionView didSelectItemAtIndexPath:(NSIndexPath * _Nonnull)indexPath;
- (nonnull instancetype)initWithCollectionViewLayout:(UICollectionViewLayout * _Nonnull)layout OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)initWithNibName:(NSString * _Nullable)nibNameOrNil bundle:(NSBundle * _Nullable)nibBundleOrNil OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)coder OBJC_DESIGNATED_INITIALIZER;
@end



@class UIPresentationController;

@interface RCRoomSelectViewController (SWIFT_EXTENSION(YaokanUISDK)) <UIPopoverPresentationControllerDelegate>
- (UIModalPresentationStyle)adaptivePresentationStyleForPresentationController:(UIPresentationController * _Nonnull)controller SWIFT_WARN_UNUSED_RESULT;
@end

@class UITextField;

@interface RCRoomSelectViewController (SWIFT_EXTENSION(YaokanUISDK)) <UITextFieldDelegate>
- (BOOL)textFieldShouldBeginEditing:(UITextField * _Nonnull)textField SWIFT_WARN_UNUSED_RESULT;
@end


@interface RCRoomSelectViewController (SWIFT_EXTENSION(YaokanUISDK)) <UICollectionViewDelegateFlowLayout>
- (CGFloat)collectionView:(UICollectionView * _Nonnull)collectionView layout:(UICollectionViewLayout * _Nonnull)collectionViewLayout minimumLineSpacingForSectionAtIndex:(NSInteger)section SWIFT_WARN_UNUSED_RESULT;
- (CGSize)collectionView:(UICollectionView * _Nonnull)collectionView layout:(UICollectionViewLayout * _Nonnull)collectionViewLayout sizeForItemAtIndexPath:(NSIndexPath * _Nonnull)indexPath SWIFT_WARN_UNUSED_RESULT;
- (UIEdgeInsets)collectionView:(UICollectionView * _Nonnull)collectionView layout:(UICollectionViewLayout * _Nonnull)collectionViewLayout insetForSectionAtIndex:(NSInteger)section SWIFT_WARN_UNUSED_RESULT;
@end


SWIFT_PROTOCOL("_TtP11YaokanUISDK34RCRoomSelectViewControllerDelegate_")
@protocol RCRoomSelectViewControllerDelegate
- (void)roomSelectViewControllerDidCancel:(RCRoomSelectViewController * _Nonnull)controller;
- (void)roomSelectViewControllerDidFinish:(RCRoomSelectViewController * _Nonnull)controller;
@end

@class YKFadeButton;

IB_DESIGNABLE
SWIFT_CLASS("_TtC11YaokanUISDK14RDAddSubButton")
@interface RDAddSubButton : UIView
@property (nonatomic, weak) IBOutlet YKFadeButton * _Null_unspecified addButton;
@property (nonatomic, weak) IBOutlet YKFadeButton * _Null_unspecified subButton;
@property (nonatomic, weak) IBOutlet UILabel * _Null_unspecified titleLabel;
- (nonnull instancetype)initWithFrame:(CGRect)frame SWIFT_UNAVAILABLE;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)aDecoder SWIFT_UNAVAILABLE;
@end


IB_DESIGNABLE
SWIFT_CLASS("_TtC11YaokanUISDK21RDAddSubButtonHorizon")
@interface RDAddSubButtonHorizon : UIView
@property (nonatomic, weak) IBOutlet UIButton * _Null_unspecified addButton;
@property (nonatomic, weak) IBOutlet UIButton * _Null_unspecified subButton;
@property (nonatomic, weak) IBOutlet UILabel * _Null_unspecified titleLabel;
- (nonnull instancetype)initWithFrame:(CGRect)frame SWIFT_UNAVAILABLE;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)aDecoder SWIFT_UNAVAILABLE;
@end

@class RDRoundButton72;

IB_DESIGNABLE
SWIFT_CLASS("_TtC11YaokanUISDK17RDAddSubGroupView")
@interface RDAddSubGroupView : UIView
@property (nonatomic, weak) IBOutlet RDAddSubButton * _Null_unspecified leftAddSubButton;
@property (nonatomic, weak) IBOutlet RDAddSubButton * _Null_unspecified rightAddSubButton;
@property (nonatomic, weak) IBOutlet RDRoundButton72 * _Null_unspecified middleTopButton;
@property (nonatomic, weak) IBOutlet RDRoundButton72 * _Null_unspecified middleBottomButton;
- (nonnull instancetype)initWithFrame:(CGRect)frame SWIFT_UNAVAILABLE;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)aDecoder SWIFT_UNAVAILABLE;
@end


SWIFT_CLASS("_TtC11YaokanUISDK15RDColorButton80")
@interface RDColorButton80 : UIButton
- (nonnull instancetype)initWithFrame:(CGRect)frame SWIFT_UNAVAILABLE;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)aDecoder SWIFT_UNAVAILABLE;
@end

@class RDCursorView;

IB_DESIGNABLE
SWIFT_CLASS("_TtC11YaokanUISDK17RDCursorGroupView")
@interface RDCursorGroupView : UIView
@property (nonatomic, weak) IBOutlet RDRoundButton72 * _Null_unspecified leftTopButton;
@property (nonatomic, weak) IBOutlet RDRoundButton72 * _Null_unspecified leftBottomButton;
@property (nonatomic, weak) IBOutlet RDRoundButton72 * _Null_unspecified rightTopButton;
@property (nonatomic, weak) IBOutlet RDRoundButton72 * _Null_unspecified rightBottomButton;
@property (nonatomic, weak) IBOutlet RDCursorView * _Null_unspecified cursorView;
- (nonnull instancetype)initWithFrame:(CGRect)frame SWIFT_UNAVAILABLE;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)aDecoder SWIFT_UNAVAILABLE;
@end


SWIFT_CLASS("_TtC11YaokanUISDK12RDCursorView")
@interface RDCursorView : UIView
@property (nonatomic, weak) IBOutlet RDRoundButton72 * _Null_unspecified upButton;
@property (nonatomic, weak) IBOutlet YKFadeButton * _Null_unspecified downButton;
@property (nonatomic, weak) IBOutlet RDRoundButton72 * _Null_unspecified leftButton;
@property (nonatomic, weak) IBOutlet RDRoundButton72 * _Null_unspecified rightButton;
@property (nonatomic, weak) IBOutlet UIButton * _Null_unspecified okButton;
- (nonnull instancetype)initWithFrame:(CGRect)frame SWIFT_UNAVAILABLE;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)aDecoder SWIFT_UNAVAILABLE;
@end


SWIFT_CLASS("_TtC11YaokanUISDK20RDLongRoundButton120")
@interface RDLongRoundButton120 : YKFadeButton
- (nonnull instancetype)initWithFrame:(CGRect)frame SWIFT_UNAVAILABLE;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)aDecoder SWIFT_UNAVAILABLE;
@end


SWIFT_CLASS("_TtC11YaokanUISDK19RDLongRoundButton80")
@interface RDLongRoundButton80 : YKFadeButton
- (nonnull instancetype)initWithFrame:(CGRect)frame SWIFT_UNAVAILABLE;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)aDecoder SWIFT_UNAVAILABLE;
@end

@class RDRoundButton104;

IB_DESIGNABLE
SWIFT_CLASS("_TtC11YaokanUISDK22RDPlayControlBasicView")
@interface RDPlayControlBasicView : UIView
@property (nonatomic, weak) IBOutlet RDRoundButton104 * _Null_unspecified previousButton;
@property (nonatomic, weak) IBOutlet RDRoundButton104 * _Null_unspecified nextButton;
@property (nonatomic, weak) IBOutlet RDLongRoundButton120 * _Null_unspecified playPauseButton;
- (nonnull instancetype)initWithFrame:(CGRect)frame SWIFT_UNAVAILABLE;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)aDecoder SWIFT_UNAVAILABLE;
@end


IB_DESIGNABLE
SWIFT_CLASS("_TtC11YaokanUISDK22RDPlayControlGroupView")
@interface RDPlayControlGroupView : UIView
@property (nonatomic, weak) IBOutlet RDPlayControlBasicView * _Null_unspecified rdPlayControlBasicView;
@property (nonatomic, weak) IBOutlet RDRoundButton104 * _Null_unspecified previousButton;
@property (nonatomic, weak) IBOutlet RDRoundButton104 * _Null_unspecified backwardButton;
@property (nonatomic, weak) IBOutlet RDRoundButton104 * _Null_unspecified forwardButton;
@property (nonatomic, weak) IBOutlet RDRoundButton104 * _Null_unspecified nextButton;
- (nonnull instancetype)initWithFrame:(CGRect)frame SWIFT_UNAVAILABLE;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)aDecoder SWIFT_UNAVAILABLE;
@end


IB_DESIGNABLE
SWIFT_CLASS("_TtC11YaokanUISDK16RDRoundButton104")
@interface RDRoundButton104 : YKFadeButton
- (nonnull instancetype)initWithFrame:(CGRect)frame SWIFT_UNAVAILABLE;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)aDecoder SWIFT_UNAVAILABLE;
@property (nonatomic, readonly) CGSize intrinsicContentSize;
@end


SWIFT_CLASS("_TtC11YaokanUISDK16RDRoundButton150")
@interface RDRoundButton150 : YKFadeButton
- (nonnull instancetype)initWithFrame:(CGRect)frame SWIFT_UNAVAILABLE;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)aDecoder SWIFT_UNAVAILABLE;
@end


SWIFT_CLASS("_TtC11YaokanUISDK16RDRoundButton153")
@interface RDRoundButton153 : YKFadeButton
- (nonnull instancetype)initWithFrame:(CGRect)frame SWIFT_UNAVAILABLE;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)aDecoder SWIFT_UNAVAILABLE;
@end


SWIFT_CLASS("_TtC11YaokanUISDK15RDRoundButton72")
@interface RDRoundButton72 : YKFadeButton
- (void)awakeFromNib;
- (nonnull instancetype)initWithFrame:(CGRect)frame OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)coder OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC11YaokanUISDK19RDRoundCornerButton")
@interface RDRoundCornerButton : YKFadeButton
- (nonnull instancetype)initWithFrame:(CGRect)frame SWIFT_UNAVAILABLE;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)aDecoder SWIFT_UNAVAILABLE;
@end


IB_DESIGNABLE
SWIFT_CLASS("_TtC11YaokanUISDK15RDShotButton133")
@interface RDShotButton133 : YKFadeButton
- (nonnull instancetype)initWithFrame:(CGRect)frame SWIFT_UNAVAILABLE;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)aDecoder SWIFT_UNAVAILABLE;
@end


IB_DESIGNABLE
SWIFT_CLASS("_TtC11YaokanUISDK14RDShotButton90")
@interface RDShotButton90 : YKFadeButton
- (nonnull instancetype)initWithFrame:(CGRect)frame SWIFT_UNAVAILABLE;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)aDecoder SWIFT_UNAVAILABLE;
@end


IB_DESIGNABLE
SWIFT_CLASS("_TtC11YaokanUISDK18RDShotButtonCamera")
@interface RDShotButtonCamera : YKFadeButton
- (nonnull instancetype)initWithFrame:(CGRect)frame SWIFT_UNAVAILABLE;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)aDecoder SWIFT_UNAVAILABLE;
@end


SWIFT_CLASS("_TtC11YaokanUISDK17RDSquareButton150")
@interface RDSquareButton150 : YKFadeButton
- (nonnull instancetype)initWithFrame:(CGRect)frame SWIFT_UNAVAILABLE;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)aDecoder SWIFT_UNAVAILABLE;
@end


SWIFT_CLASS("_TtC11YaokanUISDK17RDSquareButton176")
@interface RDSquareButton176 : YKFadeButton
- (nonnull instancetype)initWithFrame:(CGRect)frame SWIFT_UNAVAILABLE;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)aDecoder SWIFT_UNAVAILABLE;
@end


SWIFT_CLASS("_TtC11YaokanUISDK23RDSquareButton176Normal")
@interface RDSquareButton176Normal : YKFadeButton
- (nonnull instancetype)initWithFrame:(CGRect)frame SWIFT_UNAVAILABLE;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)aDecoder SWIFT_UNAVAILABLE;
@end

@class NSString;

SWIFT_CLASS("_TtC11YaokanUISDK16RDSquareButton90")
@interface RDSquareButton90 : YKFadeButton
- (nonnull instancetype)initWithFrame:(CGRect)frame SWIFT_UNAVAILABLE;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)aDecoder SWIFT_UNAVAILABLE;
- (void)awakeFromNib;
- (void)setImgWithImg:(NSString * _Nonnull)img;
- (void)setTextWithStr:(NSString * _Nonnull)str;
@end

@class UIColor;

SWIFT_CLASS("_TtC11YaokanUISDK17RDSquareButtonMPE")
@interface RDSquareButtonMPE : YKFadeButton
- (nonnull instancetype)initWithFrame:(CGRect)frame SWIFT_UNAVAILABLE;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)aDecoder SWIFT_UNAVAILABLE;
- (void)awakeFromNib;
- (void)setImgWithImg:(NSString * _Nonnull)img;
- (void)setTextWithStr:(NSString * _Nonnull)str;
- (void)setImgTinColorWithC:(UIColor * _Nonnull)c;
- (void)setTextTinColorWithC:(UIColor * _Nonnull)c;
@end


IB_DESIGNABLE
SWIFT_CLASS("_TtC11YaokanUISDK13RDTimerButton")
@interface RDTimerButton : UIView
@property (nonatomic, weak) IBOutlet UIView * _Null_unspecified timeIndicator;
@property (nonatomic, weak) IBOutlet UILabel * _Null_unspecified timeLabel;
@property (nonatomic, weak) IBOutlet RDRoundButton150 * _Null_unspecified leftButton;
@property (nonatomic, weak) IBOutlet RDRoundButton150 * _Null_unspecified rightButton;
- (nonnull instancetype)initWithFrame:(CGRect)frame SWIFT_UNAVAILABLE;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)aDecoder SWIFT_UNAVAILABLE;
- (IBAction)subTime:(YKFadeButton * _Nonnull)sender;
- (IBAction)addTime:(YKFadeButton * _Nonnull)sender;
- (NSInteger)currentTime SWIFT_WARN_UNUSED_RESULT;
@end


SWIFT_CLASS("_TtC11YaokanUISDK20RDTopButtonGroupView")
@interface RDTopButtonGroupView : UIView
@property (nonatomic, weak) IBOutlet UIButton * _Null_unspecified leftButton;
@property (nonatomic, weak) IBOutlet UIButton * _Null_unspecified middleButton;
@property (nonatomic, weak) IBOutlet UIButton * _Null_unspecified rightButton;
- (nonnull instancetype)initWithFrame:(CGRect)frame SWIFT_UNAVAILABLE;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)aDecoder SWIFT_UNAVAILABLE;
@end


IB_DESIGNABLE
SWIFT_CLASS("_TtC11YaokanUISDK14RDVolGroupView")
@interface RDVolGroupView : UIView
@property (nonatomic, strong) IBOutlet RDAddSubButton * _Null_unspecified volAddSubButton;
@property (nonatomic, weak) IBOutlet RDRoundButton72 * _Null_unspecified leftButton;
@property (nonatomic, weak) IBOutlet RDRoundButton72 * _Null_unspecified rightButton;
- (nonnull instancetype)initWithFrame:(CGRect)frame SWIFT_UNAVAILABLE;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)aDecoder SWIFT_UNAVAILABLE;
@end


@interface UIImage (SWIFT_EXTENSION(YaokanUISDK))
/// Create a grayscale image with alpha channel. Is 5 times faster than grayscaleImage().
///
/// returns:
/// The grayscale image of self if available.
- (UIImage * _Nullable)convertToGrayScale SWIFT_WARN_UNUSED_RESULT;
@end


SWIFT_CLASS("_TtC11YaokanUISDK11YKIRZipUtil")
@interface YKIRZipUtil : NSObject
+ (NSString * _Nonnull)ver SWIFT_WARN_UNUSED_RESULT;
+ (NSString * _Nullable)decodeWithEncode:(NSString * _Nonnull)encode zipType:(uint8_t)zipType SWIFT_WARN_UNUSED_RESULT;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end

#if __has_attribute(external_source_symbol)
# pragma clang attribute pop
#endif
#pragma clang diagnostic pop

#elif defined(__ARM_ARCH_7A__) && __ARM_ARCH_7A__
// Generated by Apple Swift version 5.2.4 effective-4.1.50 (swiftlang-1103.0.32.9 clang-1103.0.32.53)
#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wgcc-compat"

#if !defined(__has_include)
# define __has_include(x) 0
#endif
#if !defined(__has_attribute)
# define __has_attribute(x) 0
#endif
#if !defined(__has_feature)
# define __has_feature(x) 0
#endif
#if !defined(__has_warning)
# define __has_warning(x) 0
#endif

#if __has_include(<swift/objc-prologue.h>)
# include <swift/objc-prologue.h>
#endif

#pragma clang diagnostic ignored "-Wauto-import"
#include <Foundation/Foundation.h>
#include <stdint.h>
#include <stddef.h>
#include <stdbool.h>

#if !defined(SWIFT_TYPEDEFS)
# define SWIFT_TYPEDEFS 1
# if __has_include(<uchar.h>)
#  include <uchar.h>
# elif !defined(__cplusplus)
typedef uint_least16_t char16_t;
typedef uint_least32_t char32_t;
# endif
typedef float swift_float2  __attribute__((__ext_vector_type__(2)));
typedef float swift_float3  __attribute__((__ext_vector_type__(3)));
typedef float swift_float4  __attribute__((__ext_vector_type__(4)));
typedef double swift_double2  __attribute__((__ext_vector_type__(2)));
typedef double swift_double3  __attribute__((__ext_vector_type__(3)));
typedef double swift_double4  __attribute__((__ext_vector_type__(4)));
typedef int swift_int2  __attribute__((__ext_vector_type__(2)));
typedef int swift_int3  __attribute__((__ext_vector_type__(3)));
typedef int swift_int4  __attribute__((__ext_vector_type__(4)));
typedef unsigned int swift_uint2  __attribute__((__ext_vector_type__(2)));
typedef unsigned int swift_uint3  __attribute__((__ext_vector_type__(3)));
typedef unsigned int swift_uint4  __attribute__((__ext_vector_type__(4)));
#endif

#if !defined(SWIFT_PASTE)
# define SWIFT_PASTE_HELPER(x, y) x##y
# define SWIFT_PASTE(x, y) SWIFT_PASTE_HELPER(x, y)
#endif
#if !defined(SWIFT_METATYPE)
# define SWIFT_METATYPE(X) Class
#endif
#if !defined(SWIFT_CLASS_PROPERTY)
# if __has_feature(objc_class_property)
#  define SWIFT_CLASS_PROPERTY(...) __VA_ARGS__
# else
#  define SWIFT_CLASS_PROPERTY(...)
# endif
#endif

#if __has_attribute(objc_runtime_name)
# define SWIFT_RUNTIME_NAME(X) __attribute__((objc_runtime_name(X)))
#else
# define SWIFT_RUNTIME_NAME(X)
#endif
#if __has_attribute(swift_name)
# define SWIFT_COMPILE_NAME(X) __attribute__((swift_name(X)))
#else
# define SWIFT_COMPILE_NAME(X)
#endif
#if __has_attribute(objc_method_family)
# define SWIFT_METHOD_FAMILY(X) __attribute__((objc_method_family(X)))
#else
# define SWIFT_METHOD_FAMILY(X)
#endif
#if __has_attribute(noescape)
# define SWIFT_NOESCAPE __attribute__((noescape))
#else
# define SWIFT_NOESCAPE
#endif
#if __has_attribute(ns_consumed)
# define SWIFT_RELEASES_ARGUMENT __attribute__((ns_consumed))
#else
# define SWIFT_RELEASES_ARGUMENT
#endif
#if __has_attribute(warn_unused_result)
# define SWIFT_WARN_UNUSED_RESULT __attribute__((warn_unused_result))
#else
# define SWIFT_WARN_UNUSED_RESULT
#endif
#if __has_attribute(noreturn)
# define SWIFT_NORETURN __attribute__((noreturn))
#else
# define SWIFT_NORETURN
#endif
#if !defined(SWIFT_CLASS_EXTRA)
# define SWIFT_CLASS_EXTRA
#endif
#if !defined(SWIFT_PROTOCOL_EXTRA)
# define SWIFT_PROTOCOL_EXTRA
#endif
#if !defined(SWIFT_ENUM_EXTRA)
# define SWIFT_ENUM_EXTRA
#endif
#if !defined(SWIFT_CLASS)
# if __has_attribute(objc_subclassing_restricted)
#  define SWIFT_CLASS(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) __attribute__((objc_subclassing_restricted)) SWIFT_CLASS_EXTRA
#  define SWIFT_CLASS_NAMED(SWIFT_NAME) __attribute__((objc_subclassing_restricted)) SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_CLASS_EXTRA
# else
#  define SWIFT_CLASS(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) SWIFT_CLASS_EXTRA
#  define SWIFT_CLASS_NAMED(SWIFT_NAME) SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_CLASS_EXTRA
# endif
#endif
#if !defined(SWIFT_RESILIENT_CLASS)
# if __has_attribute(objc_class_stub)
#  define SWIFT_RESILIENT_CLASS(SWIFT_NAME) SWIFT_CLASS(SWIFT_NAME) __attribute__((objc_class_stub))
#  define SWIFT_RESILIENT_CLASS_NAMED(SWIFT_NAME) __attribute__((objc_class_stub)) SWIFT_CLASS_NAMED(SWIFT_NAME)
# else
#  define SWIFT_RESILIENT_CLASS(SWIFT_NAME) SWIFT_CLASS(SWIFT_NAME)
#  define SWIFT_RESILIENT_CLASS_NAMED(SWIFT_NAME) SWIFT_CLASS_NAMED(SWIFT_NAME)
# endif
#endif

#if !defined(SWIFT_PROTOCOL)
# define SWIFT_PROTOCOL(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) SWIFT_PROTOCOL_EXTRA
# define SWIFT_PROTOCOL_NAMED(SWIFT_NAME) SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_PROTOCOL_EXTRA
#endif

#if !defined(SWIFT_EXTENSION)
# define SWIFT_EXTENSION(M) SWIFT_PASTE(M##_Swift_, __LINE__)
#endif

#if !defined(OBJC_DESIGNATED_INITIALIZER)
# if __has_attribute(objc_designated_initializer)
#  define OBJC_DESIGNATED_INITIALIZER __attribute__((objc_designated_initializer))
# else
#  define OBJC_DESIGNATED_INITIALIZER
# endif
#endif
#if !defined(SWIFT_ENUM_ATTR)
# if defined(__has_attribute) && __has_attribute(enum_extensibility)
#  define SWIFT_ENUM_ATTR(_extensibility) __attribute__((enum_extensibility(_extensibility)))
# else
#  define SWIFT_ENUM_ATTR(_extensibility)
# endif
#endif
#if !defined(SWIFT_ENUM)
# define SWIFT_ENUM(_type, _name, _extensibility) enum _name : _type _name; enum SWIFT_ENUM_ATTR(_extensibility) SWIFT_ENUM_EXTRA _name : _type
# if __has_feature(generalized_swift_name)
#  define SWIFT_ENUM_NAMED(_type, _name, SWIFT_NAME, _extensibility) enum _name : _type _name SWIFT_COMPILE_NAME(SWIFT_NAME); enum SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_ENUM_ATTR(_extensibility) SWIFT_ENUM_EXTRA _name : _type
# else
#  define SWIFT_ENUM_NAMED(_type, _name, SWIFT_NAME, _extensibility) SWIFT_ENUM(_type, _name, _extensibility)
# endif
#endif
#if !defined(SWIFT_UNAVAILABLE)
# define SWIFT_UNAVAILABLE __attribute__((unavailable))
#endif
#if !defined(SWIFT_UNAVAILABLE_MSG)
# define SWIFT_UNAVAILABLE_MSG(msg) __attribute__((unavailable(msg)))
#endif
#if !defined(SWIFT_AVAILABILITY)
# define SWIFT_AVAILABILITY(plat, ...) __attribute__((availability(plat, __VA_ARGS__)))
#endif
#if !defined(SWIFT_WEAK_IMPORT)
# define SWIFT_WEAK_IMPORT __attribute__((weak_import))
#endif
#if !defined(SWIFT_DEPRECATED)
# define SWIFT_DEPRECATED __attribute__((deprecated))
#endif
#if !defined(SWIFT_DEPRECATED_MSG)
# define SWIFT_DEPRECATED_MSG(...) __attribute__((deprecated(__VA_ARGS__)))
#endif
#if __has_feature(attribute_diagnose_if_objc)
# define SWIFT_DEPRECATED_OBJC(Msg) __attribute__((diagnose_if(1, Msg, "warning")))
#else
# define SWIFT_DEPRECATED_OBJC(Msg) SWIFT_DEPRECATED_MSG(Msg)
#endif
#if !defined(IBSegueAction)
# define IBSegueAction
#endif
#if __has_feature(modules)
#if __has_warning("-Watimport-in-framework-header")
#pragma clang diagnostic ignored "-Watimport-in-framework-header"
#endif
@import CoreGraphics;
@import Foundation;
@import ObjectiveC;
@import UIKit;
#endif

#import <YaokanUISDK/YaokanUISDK.h>

#pragma clang diagnostic ignored "-Wproperty-attribute-mismatch"
#pragma clang diagnostic ignored "-Wduplicate-method-arg"
#if __has_warning("-Wpragma-clang-attribute")
# pragma clang diagnostic ignored "-Wpragma-clang-attribute"
#endif
#pragma clang diagnostic ignored "-Wunknown-pragmas"
#pragma clang diagnostic ignored "-Wnullability"

#if __has_attribute(external_source_symbol)
# pragma push_macro("any")
# undef any
# pragma clang attribute push(__attribute__((external_source_symbol(language="Swift", defined_in="YaokanUISDK",generated_declaration))), apply_to=any(function,enum,objc_interface,objc_category,objc_protocol))
# pragma pop_macro("any")
#endif

@class UILabel;
@class UIButton;
@class UIImageView;
@class NSLayoutConstraint;
@class NSCoder;

SWIFT_CLASS("_TtC11YaokanUISDK19LearnTipsBottomView")
@interface LearnTipsBottomView : UIView
@property (nonatomic, weak) IBOutlet UILabel * _Null_unspecified contentLabel;
@property (nonatomic, weak) IBOutlet UIButton * _Null_unspecified doneButton;
@property (nonatomic, weak) IBOutlet UIImageView * _Null_unspecified learnGuideView;
@property (nonatomic, weak) IBOutlet UIImageView * _Null_unspecified tapView;
@property (nonatomic, strong) IBOutlet NSLayoutConstraint * _Null_unspecified leadingCons;
- (void)hideDoneButtonWithHide:(BOOL)hide;
- (void)step1;
- (void)step2;
- (void)step3;
- (void)step4;
- (nonnull instancetype)initWithFrame:(CGRect)frame OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)coder OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC11YaokanUISDK13OSMBottomView")
@interface OSMBottomView : UIView
@property (nonatomic, weak) IBOutlet UIButton * _Null_unspecified falseButton;
@property (nonatomic, weak) IBOutlet UIButton * _Null_unspecified trueButton;
@property (nonatomic, weak) IBOutlet UILabel * _Null_unspecified progressLabel;
@property (nonatomic, weak) IBOutlet UILabel * _Null_unspecified contentLabel;
@property (nonatomic, weak) IBOutlet UIButton * _Null_unspecified doneBtn;
- (nonnull instancetype)initWithFrame:(CGRect)frame OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)coder OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC11YaokanUISDK22RCRoomInfoReusableView")
@interface RCRoomInfoReusableView : UICollectionReusableView
- (void)awakeFromNib;
- (nonnull instancetype)initWithFrame:(CGRect)frame OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)coder OBJC_DESIGNATED_INITIALIZER;
@end

@class UITableView;
@class UITableViewCell;
@class NSBundle;

SWIFT_CLASS("_TtC11YaokanUISDK26RCRoomNamePickerController")
@interface RCRoomNamePickerController : UITableViewController
- (void)viewDidLoad;
- (NSInteger)tableView:(UITableView * _Nonnull)tableView numberOfRowsInSection:(NSInteger)section SWIFT_WARN_UNUSED_RESULT;
- (UITableViewCell * _Nonnull)tableView:(UITableView * _Nonnull)tableView cellForRowAtIndexPath:(NSIndexPath * _Nonnull)indexPath SWIFT_WARN_UNUSED_RESULT;
- (void)tableView:(UITableView * _Nonnull)tableView didSelectRowAtIndexPath:(NSIndexPath * _Nonnull)indexPath;
- (nonnull instancetype)initWithStyle:(UITableViewStyle)style OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)initWithNibName:(NSString * _Nullable)nibNameOrNil bundle:(NSBundle * _Nullable)nibBundleOrNil OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)coder OBJC_DESIGNATED_INITIALIZER;
@end

@protocol RCRoomSelectViewControllerDelegate;
@class YKRemoteDevice;
@class NSNumber;
@class UIStoryboardSegue;
@class UICollectionView;
@class UICollectionViewCell;
@class UICollectionViewLayout;

SWIFT_CLASS("_TtC11YaokanUISDK26RCRoomSelectViewController")
@interface RCRoomSelectViewController : UICollectionViewController
@property (nonatomic, weak) id <RCRoomSelectViewControllerDelegate> _Nullable delegate;
@property (nonatomic, strong) YKRemoteDevice * _Nullable remoteDevice;
@property (nonatomic, strong) NSNumber * _Nullable isCreate;
- (void)viewDidLoad;
- (void)viewDidAppear:(BOOL)animated;
- (void)viewDidDisappear:(BOOL)animated;
@property (nonatomic, readonly) UIStatusBarStyle preferredStatusBarStyle;
@property (nonatomic, readonly) BOOL shouldAutorotate;
@property (nonatomic, readonly) UIInterfaceOrientationMask supportedInterfaceOrientations;
- (void)prepareForSegue:(UIStoryboardSegue * _Nonnull)segue sender:(id _Nullable)sender;
- (NSInteger)collectionView:(UICollectionView * _Nonnull)collectionView numberOfItemsInSection:(NSInteger)section SWIFT_WARN_UNUSED_RESULT;
- (UICollectionViewCell * _Nonnull)collectionView:(UICollectionView * _Nonnull)collectionView cellForItemAtIndexPath:(NSIndexPath * _Nonnull)indexPath SWIFT_WARN_UNUSED_RESULT;
- (UICollectionReusableView * _Nonnull)collectionView:(UICollectionView * _Nonnull)collectionView viewForSupplementaryElementOfKind:(NSString * _Nonnull)kind atIndexPath:(NSIndexPath * _Nonnull)indexPath SWIFT_WARN_UNUSED_RESULT;
- (void)collectionView:(UICollectionView * _Nonnull)collectionView didSelectItemAtIndexPath:(NSIndexPath * _Nonnull)indexPath;
- (nonnull instancetype)initWithCollectionViewLayout:(UICollectionViewLayout * _Nonnull)layout OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)initWithNibName:(NSString * _Nullable)nibNameOrNil bundle:(NSBundle * _Nullable)nibBundleOrNil OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)coder OBJC_DESIGNATED_INITIALIZER;
@end



@class UIPresentationController;

@interface RCRoomSelectViewController (SWIFT_EXTENSION(YaokanUISDK)) <UIPopoverPresentationControllerDelegate>
- (UIModalPresentationStyle)adaptivePresentationStyleForPresentationController:(UIPresentationController * _Nonnull)controller SWIFT_WARN_UNUSED_RESULT;
@end

@class UITextField;

@interface RCRoomSelectViewController (SWIFT_EXTENSION(YaokanUISDK)) <UITextFieldDelegate>
- (BOOL)textFieldShouldBeginEditing:(UITextField * _Nonnull)textField SWIFT_WARN_UNUSED_RESULT;
@end


@interface RCRoomSelectViewController (SWIFT_EXTENSION(YaokanUISDK)) <UICollectionViewDelegateFlowLayout>
- (CGFloat)collectionView:(UICollectionView * _Nonnull)collectionView layout:(UICollectionViewLayout * _Nonnull)collectionViewLayout minimumLineSpacingForSectionAtIndex:(NSInteger)section SWIFT_WARN_UNUSED_RESULT;
- (CGSize)collectionView:(UICollectionView * _Nonnull)collectionView layout:(UICollectionViewLayout * _Nonnull)collectionViewLayout sizeForItemAtIndexPath:(NSIndexPath * _Nonnull)indexPath SWIFT_WARN_UNUSED_RESULT;
- (UIEdgeInsets)collectionView:(UICollectionView * _Nonnull)collectionView layout:(UICollectionViewLayout * _Nonnull)collectionViewLayout insetForSectionAtIndex:(NSInteger)section SWIFT_WARN_UNUSED_RESULT;
@end


SWIFT_PROTOCOL("_TtP11YaokanUISDK34RCRoomSelectViewControllerDelegate_")
@protocol RCRoomSelectViewControllerDelegate
- (void)roomSelectViewControllerDidCancel:(RCRoomSelectViewController * _Nonnull)controller;
- (void)roomSelectViewControllerDidFinish:(RCRoomSelectViewController * _Nonnull)controller;
@end

@class YKFadeButton;

IB_DESIGNABLE
SWIFT_CLASS("_TtC11YaokanUISDK14RDAddSubButton")
@interface RDAddSubButton : UIView
@property (nonatomic, weak) IBOutlet YKFadeButton * _Null_unspecified addButton;
@property (nonatomic, weak) IBOutlet YKFadeButton * _Null_unspecified subButton;
@property (nonatomic, weak) IBOutlet UILabel * _Null_unspecified titleLabel;
- (nonnull instancetype)initWithFrame:(CGRect)frame SWIFT_UNAVAILABLE;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)aDecoder SWIFT_UNAVAILABLE;
@end


IB_DESIGNABLE
SWIFT_CLASS("_TtC11YaokanUISDK21RDAddSubButtonHorizon")
@interface RDAddSubButtonHorizon : UIView
@property (nonatomic, weak) IBOutlet UIButton * _Null_unspecified addButton;
@property (nonatomic, weak) IBOutlet UIButton * _Null_unspecified subButton;
@property (nonatomic, weak) IBOutlet UILabel * _Null_unspecified titleLabel;
- (nonnull instancetype)initWithFrame:(CGRect)frame SWIFT_UNAVAILABLE;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)aDecoder SWIFT_UNAVAILABLE;
@end

@class RDRoundButton72;

IB_DESIGNABLE
SWIFT_CLASS("_TtC11YaokanUISDK17RDAddSubGroupView")
@interface RDAddSubGroupView : UIView
@property (nonatomic, weak) IBOutlet RDAddSubButton * _Null_unspecified leftAddSubButton;
@property (nonatomic, weak) IBOutlet RDAddSubButton * _Null_unspecified rightAddSubButton;
@property (nonatomic, weak) IBOutlet RDRoundButton72 * _Null_unspecified middleTopButton;
@property (nonatomic, weak) IBOutlet RDRoundButton72 * _Null_unspecified middleBottomButton;
- (nonnull instancetype)initWithFrame:(CGRect)frame SWIFT_UNAVAILABLE;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)aDecoder SWIFT_UNAVAILABLE;
@end


SWIFT_CLASS("_TtC11YaokanUISDK15RDColorButton80")
@interface RDColorButton80 : UIButton
- (nonnull instancetype)initWithFrame:(CGRect)frame SWIFT_UNAVAILABLE;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)aDecoder SWIFT_UNAVAILABLE;
@end

@class RDCursorView;

IB_DESIGNABLE
SWIFT_CLASS("_TtC11YaokanUISDK17RDCursorGroupView")
@interface RDCursorGroupView : UIView
@property (nonatomic, weak) IBOutlet RDRoundButton72 * _Null_unspecified leftTopButton;
@property (nonatomic, weak) IBOutlet RDRoundButton72 * _Null_unspecified leftBottomButton;
@property (nonatomic, weak) IBOutlet RDRoundButton72 * _Null_unspecified rightTopButton;
@property (nonatomic, weak) IBOutlet RDRoundButton72 * _Null_unspecified rightBottomButton;
@property (nonatomic, weak) IBOutlet RDCursorView * _Null_unspecified cursorView;
- (nonnull instancetype)initWithFrame:(CGRect)frame SWIFT_UNAVAILABLE;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)aDecoder SWIFT_UNAVAILABLE;
@end


SWIFT_CLASS("_TtC11YaokanUISDK12RDCursorView")
@interface RDCursorView : UIView
@property (nonatomic, weak) IBOutlet RDRoundButton72 * _Null_unspecified upButton;
@property (nonatomic, weak) IBOutlet YKFadeButton * _Null_unspecified downButton;
@property (nonatomic, weak) IBOutlet RDRoundButton72 * _Null_unspecified leftButton;
@property (nonatomic, weak) IBOutlet RDRoundButton72 * _Null_unspecified rightButton;
@property (nonatomic, weak) IBOutlet UIButton * _Null_unspecified okButton;
- (nonnull instancetype)initWithFrame:(CGRect)frame SWIFT_UNAVAILABLE;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)aDecoder SWIFT_UNAVAILABLE;
@end


SWIFT_CLASS("_TtC11YaokanUISDK20RDLongRoundButton120")
@interface RDLongRoundButton120 : YKFadeButton
- (nonnull instancetype)initWithFrame:(CGRect)frame SWIFT_UNAVAILABLE;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)aDecoder SWIFT_UNAVAILABLE;
@end


SWIFT_CLASS("_TtC11YaokanUISDK19RDLongRoundButton80")
@interface RDLongRoundButton80 : YKFadeButton
- (nonnull instancetype)initWithFrame:(CGRect)frame SWIFT_UNAVAILABLE;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)aDecoder SWIFT_UNAVAILABLE;
@end

@class RDRoundButton104;

IB_DESIGNABLE
SWIFT_CLASS("_TtC11YaokanUISDK22RDPlayControlBasicView")
@interface RDPlayControlBasicView : UIView
@property (nonatomic, weak) IBOutlet RDRoundButton104 * _Null_unspecified previousButton;
@property (nonatomic, weak) IBOutlet RDRoundButton104 * _Null_unspecified nextButton;
@property (nonatomic, weak) IBOutlet RDLongRoundButton120 * _Null_unspecified playPauseButton;
- (nonnull instancetype)initWithFrame:(CGRect)frame SWIFT_UNAVAILABLE;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)aDecoder SWIFT_UNAVAILABLE;
@end


IB_DESIGNABLE
SWIFT_CLASS("_TtC11YaokanUISDK22RDPlayControlGroupView")
@interface RDPlayControlGroupView : UIView
@property (nonatomic, weak) IBOutlet RDPlayControlBasicView * _Null_unspecified rdPlayControlBasicView;
@property (nonatomic, weak) IBOutlet RDRoundButton104 * _Null_unspecified previousButton;
@property (nonatomic, weak) IBOutlet RDRoundButton104 * _Null_unspecified backwardButton;
@property (nonatomic, weak) IBOutlet RDRoundButton104 * _Null_unspecified forwardButton;
@property (nonatomic, weak) IBOutlet RDRoundButton104 * _Null_unspecified nextButton;
- (nonnull instancetype)initWithFrame:(CGRect)frame SWIFT_UNAVAILABLE;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)aDecoder SWIFT_UNAVAILABLE;
@end


IB_DESIGNABLE
SWIFT_CLASS("_TtC11YaokanUISDK16RDRoundButton104")
@interface RDRoundButton104 : YKFadeButton
- (nonnull instancetype)initWithFrame:(CGRect)frame SWIFT_UNAVAILABLE;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)aDecoder SWIFT_UNAVAILABLE;
@property (nonatomic, readonly) CGSize intrinsicContentSize;
@end


SWIFT_CLASS("_TtC11YaokanUISDK16RDRoundButton150")
@interface RDRoundButton150 : YKFadeButton
- (nonnull instancetype)initWithFrame:(CGRect)frame SWIFT_UNAVAILABLE;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)aDecoder SWIFT_UNAVAILABLE;
@end


SWIFT_CLASS("_TtC11YaokanUISDK16RDRoundButton153")
@interface RDRoundButton153 : YKFadeButton
- (nonnull instancetype)initWithFrame:(CGRect)frame SWIFT_UNAVAILABLE;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)aDecoder SWIFT_UNAVAILABLE;
@end


SWIFT_CLASS("_TtC11YaokanUISDK15RDRoundButton72")
@interface RDRoundButton72 : YKFadeButton
- (void)awakeFromNib;
- (nonnull instancetype)initWithFrame:(CGRect)frame OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)coder OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC11YaokanUISDK19RDRoundCornerButton")
@interface RDRoundCornerButton : YKFadeButton
- (nonnull instancetype)initWithFrame:(CGRect)frame SWIFT_UNAVAILABLE;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)aDecoder SWIFT_UNAVAILABLE;
@end


IB_DESIGNABLE
SWIFT_CLASS("_TtC11YaokanUISDK15RDShotButton133")
@interface RDShotButton133 : YKFadeButton
- (nonnull instancetype)initWithFrame:(CGRect)frame SWIFT_UNAVAILABLE;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)aDecoder SWIFT_UNAVAILABLE;
@end


IB_DESIGNABLE
SWIFT_CLASS("_TtC11YaokanUISDK14RDShotButton90")
@interface RDShotButton90 : YKFadeButton
- (nonnull instancetype)initWithFrame:(CGRect)frame SWIFT_UNAVAILABLE;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)aDecoder SWIFT_UNAVAILABLE;
@end


IB_DESIGNABLE
SWIFT_CLASS("_TtC11YaokanUISDK18RDShotButtonCamera")
@interface RDShotButtonCamera : YKFadeButton
- (nonnull instancetype)initWithFrame:(CGRect)frame SWIFT_UNAVAILABLE;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)aDecoder SWIFT_UNAVAILABLE;
@end


SWIFT_CLASS("_TtC11YaokanUISDK17RDSquareButton150")
@interface RDSquareButton150 : YKFadeButton
- (nonnull instancetype)initWithFrame:(CGRect)frame SWIFT_UNAVAILABLE;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)aDecoder SWIFT_UNAVAILABLE;
@end


SWIFT_CLASS("_TtC11YaokanUISDK17RDSquareButton176")
@interface RDSquareButton176 : YKFadeButton
- (nonnull instancetype)initWithFrame:(CGRect)frame SWIFT_UNAVAILABLE;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)aDecoder SWIFT_UNAVAILABLE;
@end


SWIFT_CLASS("_TtC11YaokanUISDK23RDSquareButton176Normal")
@interface RDSquareButton176Normal : YKFadeButton
- (nonnull instancetype)initWithFrame:(CGRect)frame SWIFT_UNAVAILABLE;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)aDecoder SWIFT_UNAVAILABLE;
@end

@class NSString;

SWIFT_CLASS("_TtC11YaokanUISDK16RDSquareButton90")
@interface RDSquareButton90 : YKFadeButton
- (nonnull instancetype)initWithFrame:(CGRect)frame SWIFT_UNAVAILABLE;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)aDecoder SWIFT_UNAVAILABLE;
- (void)awakeFromNib;
- (void)setImgWithImg:(NSString * _Nonnull)img;
- (void)setTextWithStr:(NSString * _Nonnull)str;
@end

@class UIColor;

SWIFT_CLASS("_TtC11YaokanUISDK17RDSquareButtonMPE")
@interface RDSquareButtonMPE : YKFadeButton
- (nonnull instancetype)initWithFrame:(CGRect)frame SWIFT_UNAVAILABLE;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)aDecoder SWIFT_UNAVAILABLE;
- (void)awakeFromNib;
- (void)setImgWithImg:(NSString * _Nonnull)img;
- (void)setTextWithStr:(NSString * _Nonnull)str;
- (void)setImgTinColorWithC:(UIColor * _Nonnull)c;
- (void)setTextTinColorWithC:(UIColor * _Nonnull)c;
@end


IB_DESIGNABLE
SWIFT_CLASS("_TtC11YaokanUISDK13RDTimerButton")
@interface RDTimerButton : UIView
@property (nonatomic, weak) IBOutlet UIView * _Null_unspecified timeIndicator;
@property (nonatomic, weak) IBOutlet UILabel * _Null_unspecified timeLabel;
@property (nonatomic, weak) IBOutlet RDRoundButton150 * _Null_unspecified leftButton;
@property (nonatomic, weak) IBOutlet RDRoundButton150 * _Null_unspecified rightButton;
- (nonnull instancetype)initWithFrame:(CGRect)frame SWIFT_UNAVAILABLE;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)aDecoder SWIFT_UNAVAILABLE;
- (IBAction)subTime:(YKFadeButton * _Nonnull)sender;
- (IBAction)addTime:(YKFadeButton * _Nonnull)sender;
- (NSInteger)currentTime SWIFT_WARN_UNUSED_RESULT;
@end


SWIFT_CLASS("_TtC11YaokanUISDK20RDTopButtonGroupView")
@interface RDTopButtonGroupView : UIView
@property (nonatomic, weak) IBOutlet UIButton * _Null_unspecified leftButton;
@property (nonatomic, weak) IBOutlet UIButton * _Null_unspecified middleButton;
@property (nonatomic, weak) IBOutlet UIButton * _Null_unspecified rightButton;
- (nonnull instancetype)initWithFrame:(CGRect)frame SWIFT_UNAVAILABLE;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)aDecoder SWIFT_UNAVAILABLE;
@end


IB_DESIGNABLE
SWIFT_CLASS("_TtC11YaokanUISDK14RDVolGroupView")
@interface RDVolGroupView : UIView
@property (nonatomic, strong) IBOutlet RDAddSubButton * _Null_unspecified volAddSubButton;
@property (nonatomic, weak) IBOutlet RDRoundButton72 * _Null_unspecified leftButton;
@property (nonatomic, weak) IBOutlet RDRoundButton72 * _Null_unspecified rightButton;
- (nonnull instancetype)initWithFrame:(CGRect)frame SWIFT_UNAVAILABLE;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)aDecoder SWIFT_UNAVAILABLE;
@end


@interface UIImage (SWIFT_EXTENSION(YaokanUISDK))
/// Create a grayscale image with alpha channel. Is 5 times faster than grayscaleImage().
///
/// returns:
/// The grayscale image of self if available.
- (UIImage * _Nullable)convertToGrayScale SWIFT_WARN_UNUSED_RESULT;
@end


SWIFT_CLASS("_TtC11YaokanUISDK11YKIRZipUtil")
@interface YKIRZipUtil : NSObject
+ (NSString * _Nonnull)ver SWIFT_WARN_UNUSED_RESULT;
+ (NSString * _Nullable)decodeWithEncode:(NSString * _Nonnull)encode zipType:(uint8_t)zipType SWIFT_WARN_UNUSED_RESULT;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end

#if __has_attribute(external_source_symbol)
# pragma clang attribute pop
#endif
#pragma clang diagnostic pop

#endif
